name: github_test_A의 서브모듈 포인터 자동 업데이트

on:
  push:
    branches:
      - master  # github_test_B에서 master 브랜치 푸시될 때 실행

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    env:
      GIT_USERNAME: "Jinsun-Lee"
      GIT_EMAIL: "012vision@gmail.com"
      GITHUB_ID: "Jinsun-Lee"      
      
      REPO_A: "coding_test"                  # 메인 레포 (서브모듈 포함)
      REPO_B: "CT_Cotehap"                   # 서브모듈 레포
      BRANCH: "master"                       # 사용할 브랜치
      SUBMODULE_PATH: "FIXED/study/cotehap"  # 레포A 내부에서의 서브모듈 위치

    steps:
      - name: github_test_A 클론 + 서브모듈 포함 체크아웃
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_ID }}/${{ env.REPO_A }}
          token: ${{ secrets.LOGIN_TOKEN }}
          submodules: 'recursive'
          ref: ${{ env.BRANCH }}

      - name: Git 사용자 정보 설정
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: 서브모듈 URL 인증 토큰 포함으로 변경
        run: |
          git config -f .gitmodules submodule.${{ env.SUBMODULE_PATH }}.url https://x-access-token:${{ secrets.LOGIN_TOKEN }}@github.com/${{ env.GITHUB_ID }}/${{ env.REPO_B }}.git
          git submodule sync

      - name: 서브모듈 최신 커밋으로 업데이트
        run: |
          git submodule update --remote --checkout
          git add $SUBMODULE_PATH
          COMMIT_MSG=$(cd $SUBMODULE_PATH && git log -1 --pretty=%B)
          git commit -m "[코테합]$COMMIT_MSG" || echo "변경 없음"
          git push origin $BRANCH
